before_install:
  - sudo dpkg --purge sbt
  - sudo rm -Rf /etc/sbt/ /usr/bin/sbt
  - wget http://scalasbt.artifactoryonline.com/scalasbt/sbt-native-packages/org/scala-sbt/sbt/0.12.2/sbt.deb -O /tmp/sbt.deb
  - sudo dpkg -i /tmp/sbt.deb
language: scala
scala:
   - 2.10.0
